config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root :to => 'recipes#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'devise/registrations#new', as: :unauthenticated_root
    end
  end

  resources :foods, except: :update
  resources :recipes, except: :update do
    resources :recipe_foods
  end
  resources :users
  get 'public_recipes', to: 'recipes#public_recipes'
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_food, dependent: :destroy
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = current_user.recipes.order(:id)
  end

  def show
    @recipe = Recipe.includes(@food).find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = current_user.recipes.new(recipe_params)
    respond_to do |format|
      format.html do
        if @recipe.save
          flash[:success] = 'Recipe saved successfully'
          redirect_to recipes_path(@recipe)
        else
          flash.now[:error] = 'Error: Recipe could not be saved'
          redirect_to new_recipe_path
        end
      end
    end
  end

  def destroy
    @recipe = current_user.recipes.find(params[:id])
    @recipe.destroy
    redirect_to recipes_url notice: 'Recipe was successfully destroyed.'
  end

  def public_recipes
    @recipes = Recipe.where(public: 't')
  end

  protected

  def recipe_params
    params
      .require(:recipe)
      .permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/index.html.erb
<%= render 'shared/navbar' %>

<div class = "container content mt-5 pb-6">
  <h1> Welcome to your Recipes!</h1>
    <% if @recipes.empty? %>

    <h3 class="">You have no Recipes yet!</h3>
    <p class="">Try adding from the Add recipe food button below</p>

    <% else %>
      <% @recipes.each do |recipe| %>
      <div class="recipes columns mt-4 box">
          <div class="column">
            <h2><%= recipe.name %></h2>
            <% if can? :destroy ,recipe %>
              <%= link_to  "DETAILS", recipe_path(recipe), class:"mt-2" %>
              <%= button_to "REMOVE", recipe, method: :delete, class:"button is-danger is-small mt-2" %></td>
            <% end %>
          </div>
          <div class="description column mr-6">
            <p class=""><%= recipe.description %></p>
          </div> 
      </div>
      <% end %>
      <% end %>
      <%= link_to  "Add a recipe", new_recipe_path, class:"button is-primary" %>
</div>

app/views/recipes/new.html.erb
<%= render 'shared/navbar' %>

<div class="columns mt-6">
   <%= form_with model: @recipe, url: recipes_path, method: :post, local: true, scope: :recipe do |form| %>
     <% if @recipe.errors.any? %>
       <div style="color: red">
         <h2><%= pluralize(@recipe.errors.size, "error") %> prohibited this recipe from being saved:</h2>
   
         <ul>
           <% @recipe.errors.each do |error| %>
             <li><%= error.full_message %></li>
           <% end %>
         </ul>
       </div>
     <% end %>
   
     <div class="form-group">
       <%= form.label :name, style: "display: block" %>
       <%= form.text_field :name, class:"form-control" %>
     </div>
   
     <div class="form-group">
       <%= form.label :preparation_time, style: "display: block" %>
       <%= form.text_field :preparation_time, class:"form-control" %>
     </div>
   
     <div class="form-group">
       <%= form.label :cooking_time, style: "display: block" %>
       <%= form.text_field :cooking_time, class:"form-control" %>
     </div>
   
     <div class="form-group">
       <%= form.label :description, style: "display: block" %>
       <%= form.text_area :description, class:"form-control" %>
     </div>
   
     <label >
      <%= form.check_box :public %>
      <div>Public</span>
     </label>
   
     <div>
       <%= form.submit class:"btn btn-secondary" %>
     </div>
   <% end %>
</div>

app/views/recipes/public_recipes.html.erb
<%= render 'shared/navbar' %>
<div class="container content mt-6">

  <h1 class="">Public Recipes</h1>
  
  <% if @recipes.empty? %>
  <p class="">Sorry, there are no public recipes at the moment. Check back later.</p>
  <% end %>

  <% @recipes.each do |recipe| %>
    <div class="recipes columns mt-4 box">
        <div class="column">
          <h2><%= link_to (recipe.name), recipe_path(recipe)%></h2>
          <p class="mt-5">by: <%= recipe.user.name %></p>
          <% if can? :manage, recipe %>
           <%= button_to "REMOVE", recipe_path(recipe), method: :delete, data: { confirm: "Are you sure?" }, class: "button is-danger" %>
          <% end %>
        </div>
        <div class="description column mr-6">
          <p class=""><%= recipe.description %></p>
        </div> 
    </div>
  <% end %>
</div>

app/views/recipes/show.html.erb
<%= render 'shared/navbar' %>

<div class="container content mt-6">
  <h1 class="align-self-center"><%= @recipe.name %></h1>
  <div class="is-flex is-justify-content-space-between mt-5">
    <h6>Preparation time: <%= @recipe.preparation_time %></h6>

    <label class="inline-flex relative items-center mb-5 cursor-pointer">
      <% if @recipe.public %>
        <input type="checkbox" value="" class="sr-only peer" checked disabled> Public
      <%else%>
        <input type="checkbox" value="" class="sr-only peer" disabled> Not Public
      <% end %>
    </label>

  </div>
  <h6>Cooking time: <%= @recipe.cooking_time %></h6>
  <%# <%= @recipe.description % %>
  <p class="mt-5">Steps go here....<p>

  <div class="is-flex is-justify-content-space-aroun mt-5">
    <% if @recipe.user == current_user %>
      <%= link_to  "Generate shopping list", recipe_recipe_foods_path(@recipe.id), class:"button is-primary" %>
      <%= link_to  "Add Ingredient", new_recipe_recipe_food_path(@recipe.id), class:"button is-primary ml-6" %>
    <% end %>
  </div>
  <hr class="my-5 py-1 bg-dark"/>
  <table class="table is-bordered is-striped">
  <thead class="container">
    <tr class="row">
      <th class="col">Food</th>
      <th class="col">Quantity</th>
      <th class="col">Value</th>
      <th class="col">Action</th>
    </tr>
  </thead>
  <tbody>
    <% @recipe.recipe_food.each do |recipe| %>
    <tr class="row">
      <td class="col"><%= recipe.food.name %></td>
      <td class="col"><%= recipe.quantity %></td>
      <td class="col">$<%= recipe.quantity * recipe.food.price %></td>
      <td class="col d-flex">
         <%# <%= link_to  "MODIFY", recipe_path(@recipe), class:"btn btn-primary me-4" % %>
         <%= button_to "REMOVE", recipe_recipe_food_path(@recipe.id, recipe.id), method: :delete, class:"btn btn-danger" %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>