config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root :to => 'recipes#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'devise/registrations#new', as: :unauthenticated_root
    end
  end

  resources :foods, except: :update
  resources :recipes, except: :update do
    resources :recipe_foods
  end
  resources :users
  get 'public_recipes', to: 'recipes#public_recipes'
end

app/views/shared/_flash.html.erb
<%# the if statement makes the alerts disappear from the about page since we don't need them. %>

<% if flash[:notice] %>
<div class = "alert alert-info mt-4" role= "alert">
<%= flash[:notice] %>
</div>
<% end %>
<% if flash[:alert] %>
<div class = "alert alert-warning mt-4" role="alert">
<%= flash[:alert] %>
</div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="https://bulma.io">
      <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28">
    </a>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <a href="<%= foods_path %>" class="navbar-item">
        Food
      </a>

      <a href="<%= recipes_path %>" class="navbar-item">
        Recipes
      </a>

      <a href="<%= public_recipes_path %>" class="navbar-item">
        Public Recipes
      </a>

      <a href="<%= users_path %>" class="navbar-item">
        Users
      </a>

    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">

          <% if user_signed_in? %>
            <p>
              <strong><%= button_to "Sign out", '/users/sign_out', method: :delete, class:"button is-danger" %></strong>
            </p>
          <% else %>
            <a href="<%= new_user_registration_path %>" class="button is-primary">
              <strong>Sign up</strong>
            </a>
          <% end %>
          
          <a href="<%= new_user_session_path %>" class="button is-light">
            Log in
          </a>
        </div>
      </div>
    </div>
  </div>
</nav>