config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root :to => 'recipes#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'devise/registrations#new', as: :unauthenticated_root
    end
  end

  resources :foods, except: :update
  resources :recipes, except: :update do
    resources :recipe_foods
  end
  resources :users
  get 'public_recipes', to: 'recipes#public_recipes'
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user, foreign_key: 'user_id'
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[show edit update destroy]

  # GET /foods or /foods.json
  def index
    @foods = Food.all
  end

  # GET /foods/1 or /foods/1.json
  def show; end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit; end

  # POST /foods or /foods.json
  def create
    @food = Food.new(food_params)
    @food.user = current_user

    respond_to do |format|
      if @food.save
        format.html { redirect_to food_url(@food), notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1 or /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to food_url(@food), notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    @food.destroy

    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_food
    @food = Food.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_food.html.erb
<div id="<%= dom_id food %>">
  <td><%= food.name %></td>
  <td><%= food.measurement_unit %></td>
  <td>$<%= food.price %></td>
  <td><%= food.quantity %></td>
</div>

app/views/foods/_form.html.erb
<%= form_with(model: food) do |form| %>
  <% if food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
        <% food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :measurement_unit, style: "display: block" %>
    <%= form.text_field :measurement_unit %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<h1>Editing food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Show this food", @food %> |
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/foods/index.html.erb
<%# <p style="color: green"><%= notice %</p> %>
<%= render 'shared/navbar' %>
<div class="container">
  <button class="column mt-6 is-offset-11"><%= link_to "Add Food",  new_food_path %></button>
  
  <div class=" columns mt-6 is-centered">
    <% if @foods.empty? %>
  
      <h3 class="text-center">You have no food yet!</h3>
      <p class="text-center">Try adding from the New food button below</p>
  
    <% else %>
  <table class="table is-bordered is-striped">
    <thead>
      <th><strong>Food</strong></th>
      <th><strong>Measurement unit</strong></th>
      <th><strong>Unit Price</strong></th>
      <th><strong>Quantity</strong></th>
      <th><strong>Actions</strong></th>
    <thead>
    <tbody>
      <% @foods.each do |food| %>
      <tr>
        <%= render food %>
        <td><%= button_to "Destroy this food", food, method: :delete %></td>
      <% end %>
  
      <% end %>
      </tr>
    </tbody>
  </table>
  </div>
</div>

app/views/foods/new.html.erb
<%= render 'shared/navbar' %>

<div class="content mt-6">
  <h1>New food</h1>
  
  <%= render "form", food: @food %>
  
  <br>
  
  <div>
    <%= link_to "Back to foods", foods_path %>
  </div>
</div>

app/views/foods/show.html.erb
<%= render 'shared/navbar' %>

<div class="content mt-6">
  <%# <%= render @food %>
  <p><strong>Name: </strong><%= @food.name %></p>

  <p><strong>Measurement unit: </strong><%= @food.measurement_unit %></p>

  <p><strong>Price: </strong>$ <%= @food.price %></p>

  <p><strong>Quantity: </strong><%= @food.quantity %></p>
  
  <div>
    <%= link_to "Edit this food", edit_food_path(@food) %> |
    <%= link_to "Back to foods", foods_path %>
  
    <%# <%= button_to "Destroy this food", @food, method: :delete %>
  </div>
</div>